//! Keeps `target/<profile>/static/` in step with the repo's `static/`.
//!
//! **The drift this exists to stop.** `roommate.exe` prefers a `static/`
//! directory beside the executable over the working directory (see
//! `viewer_root` in `src/main.rs` -- that preference is what makes an installed
//! build work from any working directory, so it is not the thing to change).
//! The consequence is that `target/release/roommate.exe` serves
//! `target/release/static/`, and nothing used to put the repo's files there.
//! On 2026-08-30 that copy was four weeks stale; on 2026-09-04 it was five days
//! stale and cost an afternoon, because the symptom is a frontend feature that
//! is simply absent while the binary, the data and the source are all correct.
//!
//! **Why it only ever REFRESHES a directory that already exists.** Creating one
//! would change what `cargo run` serves: a debug build has no `static/` beside
//! it, falls back to the repo's own `static/`, and so picks up an edited file on
//! a plain browser reload with no rebuild. That is the loop the viewer is
//! actually developed in, and seeding `target/debug/static/` would replace it
//! with a copy that goes stale between builds -- reintroducing this exact bug
//! in the one place it never occurred. So: if the directory is there, someone
//! is serving from it and it must be current; if it is not, nothing is
//! shadowing the repo and there is nothing to fix.
//!
//! This does not make a build reproducible from a clean checkout on its own --
//! a fresh `target/` has no `static/` to refresh, and a release run from the
//! crate root falls back to the repo's copy exactly as before.

use std::path::{Path, PathBuf};
use std::{env, fs, io};

fn main() {
    // Re-run when any viewer file changes -- including the committed renderer
    // bundle, which is generated by `npm run build` and is the half of the pair
    // that went stale in the browser.
    println!("cargo:rerun-if-changed=static");

    let Some(dest) = profile_static_dir() else {
        return;
    };
    // Not `is_dir` on a path we then create: the whole rule is that an absent
    // directory stays absent. See the header.
    if !dest.is_dir() {
        return;
    }

    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("static");
    if let Err(err) = sync_dir(&src, &dest) {
        // A warning, never a hard failure. A locked file (a running server on
        // Windows holds one) must not break the build -- the copy being stale
        // is the ordinary bug this guards, and a build that refuses to finish
        // would be a worse one.
        println!("cargo:warning=could not refresh {}: {err}", dest.display());
    }
}

/// `target/<profile>/` derived from `OUT_DIR`, which cargo sets to
/// `target/<profile>/build/<pkg>-<hash>/out` -- so the profile directory is
/// three levels up. Read from the environment rather than assembled from
/// `PROFILE`, because a custom `--target-dir` or a cross build moves the whole
/// tree and only `OUT_DIR` knows where it went.
fn profile_static_dir() -> Option<PathBuf> {
    let out_dir = env::var_os("OUT_DIR")?;
    Some(Path::new(&out_dir).ancestors().nth(3)?.join("static"))
}

/// Copy every file in `src` over `dest`, recursively.
///
/// Copies rather than syncs: files are only ever added or overwritten, never
/// deleted from `dest`. A file removed from `static/` therefore lingers in the
/// copy -- accepted deliberately, because the failure it could cause (serving a
/// page nothing links to) is inert next to the one this fixes, and a build
/// script that deletes paths it derived from an environment variable is a much
/// worse thing to get wrong.
fn sync_dir(src: &Path, dest: &Path) -> io::Result<()> {
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let from = entry.path();
        let to = dest.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            fs::create_dir_all(&to)?;
            sync_dir(&from, &to)?;
        } else {
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}
