# License:
#
#
# Revit Batch Processor Sample Code
#
# BSD License
# Copyright 2026, Jan Christel
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

# - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# - Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# This software is provided by the copyright holder "as is" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed.
# In no event shall the copyright holder be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits;
# or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage.
#
#
#

"""Which RoomMate, and which duHast, is actually running.

**This is the check that decides.** The installer can see that a duHast exists
somewhere; only here, in the session that is about to export, is it known which
copy won -- and which copy wins is not a matter of what is installed. Two
extensions can each carry a package called `duHast`, `sys.path` order picks
between them, and a module already imported by an earlier command stays for the
life of the Revit session whatever the path says.

That matters because duHast decides what an export MEANS. An item's level, a
door's footprint, whether a hole in a floor is a hole: each was wrong in an
older duHast, each was fixed upstream, and in every case the export still
*looked* successful. "Check which duHast the extension is running" has been the
first step of three separate investigations, and until now it could only be
answered by reading files on disk and guessing.

So every run prints three things -- the RoomMate build, the duHast build, and
where that duHast was loaded FROM -- and warns when the answer is not the one
the build intended. Nothing here stops a run: an unexpected duHast is usually
somebody's deliberate dev setup, and a warning that blocks work gets removed.
"""

import os


# The stamp file's own name, in both packages. Written by the build, never
# committed: a copy without one is a copy nobody built, which reads as
# "unknown" rather than as an error. See RoomMate.extension/lib/README.md.
UNKNOWN = "unknown"


def _describe(module):
    """`describe()` from a `_build_info` module, defensively.

    The stamp is generated by two different build scripts in two different
    repositories, so this treats it as data rather than as an API: a missing
    module, a missing function or a raising one all mean the same thing here,
    and none of them is worth failing an export over."""
    if module is None:
        return UNKNOWN
    try:
        return module.describe()
    except Exception:
        return UNKNOWN


def _build_info_of(package_name):
    """The `_build_info` module inside `package_name`, or None."""
    try:
        module = __import__(package_name + "._build_info", fromlist=["_build_info"])
    except Exception:
        return None
    return module


def _package_dir(package_name):
    """The directory `package_name` was imported from, or None.

    `__file__` rather than `__path__`: IronPython and CPython agree on the
    former for an ordinary package, and this only ever needs the folder."""
    try:
        package = __import__(package_name)
        return os.path.dirname(os.path.abspath(package.__file__))
    except Exception:
        return None


def _expected_lib_dir():
    """The lib folder this copy of room_m was loaded from.

    A built extension has `lib/room_m` and `lib/duHast` side by side, so the
    duHast that SHOULD win is the one in this folder. Derived from `__file__`
    rather than from a setting, because the question is about the file layout
    and nothing else can answer it."""
    utils_dir = os.path.dirname(os.path.abspath(__file__))
    room_m_dir = os.path.dirname(utils_dir)
    return os.path.dirname(room_m_dir)


def _same_dir(left, right):
    if not left or not right:
        return False
    return os.path.normcase(os.path.normpath(left)) == os.path.normcase(os.path.normpath(right))


def build_lines():
    """The run's provenance as `(lines, warnings)`, both lists of strings.

    Split from the reporting below so the facts can be gathered without a
    `Result` or a pyRevit output window -- which is what lets this be tested
    outside Revit, where every other part of it has to be taken on trust."""
    lines = []
    warnings = []

    room_m_info = _build_info_of("room_m")
    duhast_info = _build_info_of("duHast")

    room_m_build = _describe(room_m_info)
    duhast_build = _describe(duhast_info)
    duhast_dir = _package_dir("duHast")
    expected_lib = _expected_lib_dir()

    lines.append("RoomMate extractor: {}".format(room_m_build))
    lines.append("duHast: {} loaded from {}".format(duhast_build, duhast_dir or UNKNOWN))

    if duhast_dir is None:
        warnings.append(
            "duHast could not be located on disk. The export will fail if it "
            "cannot be imported at all.")
        return lines, warnings

    # Is this the duHast shipped beside room_m, or somebody else's?
    if not _same_dir(os.path.dirname(duhast_dir), expected_lib):
        warnings.append(
            "duHast was loaded from {}, not from this extension's own lib "
            "folder ({}). Another extension's copy has won, so what this export "
            "MEANS is decided by a duHast RoomMate did not ship.".format(
                duhast_dir, expected_lib))

    # Is it the commit this RoomMate was built against?
    pinned = getattr(room_m_info, "DUHAST_COMMIT", None) if room_m_info else None
    loaded = getattr(duhast_info, "COMMIT", None) if duhast_info else None
    if pinned and loaded and pinned != UNKNOWN and loaded != UNKNOWN:
        if pinned != loaded:
            warnings.append(
                "duHast is at {}, but this RoomMate was built against {}. The "
                "export may differ from what the server expects.".format(
                    loaded[:8], pinned[:8]))
    elif pinned and pinned != UNKNOWN:
        # A stamped RoomMate against an unstamped duHast: every copy deployed
        # before the stamp existed looks like this, so it is a note and not a
        # complaint -- but it does mean the check above could not run.
        lines.append(
            "duHast carries no build stamp, so it cannot be compared against "
            "the {} this RoomMate was built for.".format(pinned[:8]))

    if getattr(duhast_info, "DIRTY", False):
        lines.append("duHast was deployed from an edited working tree.")

    return lines, warnings


def report_build(return_value, output=None):
    """Record the run's provenance on `return_value`, and show any warning.

    Called once at the top of a run, before a document is picked: a run that
    goes wrong from here on has its answer to "which duHast was that?" already
    written down, in the same place as everything else the run reports.

    `output` is pyRevit's, and optional only so this can be exercised outside
    Revit. Warnings go through `append_message` rather than `update_sep`: none
    of this makes a run a failure, and reddening a run over a dev setup is how
    a warning gets ignored."""
    lines, warnings = build_lines()

    for line in lines:
        return_value.append_message(line)
    for warning in warnings:
        return_value.append_message("WARNING: {}".format(warning))

    if output is not None:
        try:
            for line in lines:
                output.print_md("- {}".format(line))
            for warning in warnings:
                output.print_md("- **WARNING: {}**".format(warning))
        except Exception:
            # An output window that cannot print is not a reason to lose a run;
            # the same text is already on `return_value`.
            pass

    return return_value
