<#
.SYNOPSIS
    Builds RoomMate-Setup-<version>.exe.

.DESCRIPTION
    Compiles the release binaries, checks the pieces the installer cannot
    check for itself, then runs the Inno Setup compiler over roommate.iss.
    Output lands in target\installer\.

    Only the BUILD machine needs Inno Setup. Install it once with:

        winget install JRSoftware.InnoSetup

.PARAMETER SkipBuild
    Package whatever is already in target\release. Useful when iterating on the
    installer itself; wrong for anything you intend to hand to someone.

.PARAMETER IsccPath
    Full path to ISCC.exe, if it is somewhere this script does not look.

.PARAMETER Version
    Version to stamp the installer with. Defaults to the crate version in
    Cargo.toml. The release workflow passes the git TAG instead, because the tag
    is what a downloaded artifact is identified by -- and the two have drifted:
    Cargo.toml says 0.1.0 while the published tags say 0.0.1-beta.N. Stamping a
    tagged release from Cargo.toml would put a version in Add/Remove Programs
    that never moves, and since AppId is fixed on purpose, every build would
    look like an upgrade of a thing that stayed the same version.
#>
[CmdletBinding()]
param(
    [switch] $SkipBuild,
    [string] $IsccPath,
    [string] $Version
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$Iss      = Join-Path $PSScriptRoot 'roommate.iss'
$OutDir   = Join-Path $RepoRoot 'target\installer'

# Cargo.toml is the default source of version truth; the .iss only carries a
# fallback for someone compiling it by hand. Keeping those in sync by hand is
# exactly the kind of thing that ships a "0.1.0" installer for a 0.3 build.
if (-not $Version) {
    $cargoToml = Get-Content (Join-Path $RepoRoot 'Cargo.toml') -Raw
    if ($cargoToml -notmatch '(?m)^version\s*=\s*"([^"]+)"') {
        throw "Could not read version from Cargo.toml"
    }
    $Version = $Matches[1]
}
$Version = $Version -replace '^v', ''

# Inno needs TWO versions and only one of them may be free text. AppVersion is
# the display string -- the setup filename, the Add/Remove Programs entry --
# and takes a tag like "0.0.1-beta.4" happily. VersionInfoVersion is the
# Windows FILE version resource, which must be purely numeric with at most four
# parts; handed the same string it is a compile error, not a warning. So the
# numeric one is derived here rather than left to whoever writes the tag.
if ($Version -notmatch '^(\d+(?:\.\d+){0,3})') {
    throw "Version '$Version' does not start with a number -- Inno cannot build a file version from it."
}
$core          = $Matches[1]
$parts         = $core.Split('.').Count
$tail          = $Version.Substring($core.Length)
$NumericVersion = $core

# A trailing number in the pre-release tail becomes the next component, so
# beta.3 and beta.4 are distinguishable file versions instead of both being
# 0.0.1 -- which is what "which build is actually installed?" comes down to
# once the tag text has been stripped away.
if ($parts -lt 4 -and $tail -match '(\d+)\s*$') {
    $NumericVersion = $core + ('.0' * (3 - $parts)) + '.' + $Matches[1]
}

Write-Host "RoomMate $Version (file version $NumericVersion)" -ForegroundColor Cyan

if (-not $SkipBuild) {
    Write-Host 'Building release binaries...' -ForegroundColor Cyan
    Push-Location $RepoRoot
    try {
        cargo build --release --bin roommate --bin mcp
        if ($LASTEXITCODE -ne 0) { throw 'cargo build failed' }
    } finally {
        Pop-Location
    }
}

foreach ($exe in 'roommate.exe', 'mcp.exe') {
    $path = Join-Path $RepoRoot "target\release\$exe"
    if (-not (Test-Path $path)) { throw "Missing $path -- run without -SkipBuild." }
}

# The renderer bundle is generated by `npm run build` and committed, so a clone
# with no node still packages a working viewer. What this cannot tell you is
# whether the committed copy is CURRENT -- .github\workflows\frontend.yml
# rebuilds and diffs it, and that is the check that catches a stale one. If you
# have touched src-js\ since the last commit, run `npm run build` first.
$bundle = Join-Path $RepoRoot 'static\vendor\renderer.bundle.js'
if (-not (Test-Path $bundle)) {
    throw "Missing $bundle -- run ``npm run build`` before packaging."
}

if (-not $IsccPath) {
    $candidates = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
        "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe"
    )
    $IsccPath = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $IsccPath) {
        $cmd = Get-Command 'ISCC.exe' -ErrorAction SilentlyContinue
        if ($cmd) { $IsccPath = $cmd.Source }
    }
}
if (-not $IsccPath) {
    throw "Inno Setup compiler not found. Install it with: winget install JRSoftware.InnoSetup"
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

Write-Host "Compiling installer with $IsccPath ..." -ForegroundColor Cyan
& $IsccPath "/DAppVersion=$Version" "/DAppNumericVersion=$NumericVersion" $Iss
if ($LASTEXITCODE -ne 0) { throw 'Inno Setup compilation failed' }

$setup = Join-Path $OutDir "RoomMate-Setup-$Version.exe"
Write-Host ''
Write-Host "Built $setup" -ForegroundColor Green
Get-Item $setup | Select-Object Name, @{ n = 'MB'; e = { [math]::Round($_.Length / 1MB, 1) } }
