; RoomMate installer -- Inno Setup 6.3 or newer.
;
; Build it with installer\build.ps1, which compiles the release binaries first
; and passes the crate version in on the command line. Compiling this file on
; its own works too, but only if target\release already holds a current build.
;
; Shape of the install, and why:
;
;   %LOCALAPPDATA%\Programs\RoomMate   the app -- both binaries, the viewer's
;                                      static files, the settings template
;   %LOCALAPPDATA%\RoomMate            everything writable -- settings the UI
;                                      edits, and the snapshot store
;
; Per-user, not Program Files, so no admin rights are needed and both writable
; locations are genuinely writable. The split matters on upgrade: the app half
; is replaced wholesale, the data half is only ever seeded when absent.

#ifndef AppVersion
  #define AppVersion "0.0.1"
#endif

; The Windows FILE version, which is NOT the same thing as AppVersion above.
; AppVersion is free text and carries the tag verbatim ("0.0.1-beta.4");
; VersionInfoVersion must be purely numeric with at most four parts, and is a
; compile ERROR rather than a warning when it is not. build.ps1 derives the
; numeric form from the tag and passes it in; this fallback is for a hand
; compile, where AppVersion above is already numeric.
#ifndef AppNumericVersion
  #define AppNumericVersion AppVersion
#endif

#define AppName    "RoomMate"
#define AppExeName "roommate.exe"
#define DataRoot   "{localappdata}\RoomMate"

[Setup]
; Never reuse this GUID for anything else -- it is how Windows recognises an
; upgrade of this app rather than a second copy of it.
AppId={{b138d5aa-8b00-4854-aa65-9439e6f575ce}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
VersionInfoVersion={#AppNumericVersion}
DefaultDirName={localappdata}\Programs\RoomMate
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=auto
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName} {#AppVersion}

; lowest: this installs into the user's own profile, so asking for elevation
; would be a prompt that buys nothing. Nothing here writes outside %LOCALAPPDATA%.
PrivilegesRequired=lowest

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

OutputDir=..\target\installer
OutputBaseFilename=RoomMate-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The two binaries. mcp.exe is not launched by any shortcut -- an MCP host
; spawns it as a child process -- but it belongs to the same install and must
; not drift from the server it shares a storage root with.
Source: "..\target\release\roommate.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\target\release\mcp.exe";      DestDir: "{app}"; Flags: ignoreversion

; The viewer. Includes static\vendor\renderer.bundle.js, which is generated by
; `npm run build` and committed -- so packaging needs no node toolchain, but a
; stale committed bundle ships a stale renderer. build.ps1 checks it exists; it
; cannot check it is current, which is what the frontend CI workflow is for.
Source: "..\static\*"; DestDir: "{app}\static"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "RoomMate.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "README-INSTALL.txt"; DestDir: "{app}"; Flags: ignoreversion isreadme

; The settings template, kept in the app directory as well as seeded below.
; The launcher re-seeds from it when the data folder is missing, which is what
; makes deleting that folder a reset instead of a broken install.
;
; ONE project file, not the whole settings\projects directory. The others in
; the repo are somebody's real jobs and sample plates; seeding them would open
; a fresh install on five projects nobody created, holding no data, and the
; only way to tell that from a broken push is to know this repo. Adding a
; project is what the settings page is for.
Source: "server.toml";               DestDir: "{app}\settings-template";          Flags: ignoreversion
Source: "..\settings\projects\sample-project.toml"; DestDir: "{app}\settings-template\projects"; Flags: ignoreversion

; The user's own copies. onlyifdoesntexist + uninsneveruninstall together mean:
; an upgrade never overwrites an edited project file, and an uninstall never
; deletes one. Losing a project's classification tiers to a routine upgrade is
; not recoverable from anywhere else.
Source: "server.toml";                 DestDir: "{#DataRoot}\settings";          Flags: onlyifdoesntexist uninsneveruninstall
Source: "..\settings\projects\sample-project.toml"; DestDir: "{#DataRoot}\settings\projects"; Flags: onlyifdoesntexist uninsneveruninstall

[Dirs]
; The snapshot store. Created empty and left behind on uninstall -- it holds
; pushed model data that exists nowhere else on this machine.
Name: "{#DataRoot}\data\snapshots"; Flags: uninsneveruninstall

[Icons]
; The shortcut runs the launcher, not roommate.exe: the server needs its two
; settings paths and a browser opened once the port answers. -ExecutionPolicy
; Bypass so a locked-down machine policy does not make the shortcut a no-op;
; it applies to this one invocation only. The icon is taken from the server
; binary so the shortcut does not look like a PowerShell script.
Name: "{group}\{#AppName}"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\RoomMate.ps1"""; \
    WorkingDir: "{app}"; IconFilename: "{app}\{#AppExeName}"; \
    Comment: "Start the RoomMate server and open the viewer"

Name: "{group}\RoomMate data folder"; Filename: "{#DataRoot}"

Name: "{autodesktop}\{#AppName}"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\RoomMate.ps1"""; \
    WorkingDir: "{app}"; IconFilename: "{app}\{#AppExeName}"; Tasks: desktopicon

Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"

[Run]
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\RoomMate.ps1"""; \
    WorkingDir: "{app}"; Description: "Start {#AppName} now"; \
    Flags: postinstall nowait skipifsilent unchecked
